//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiSakFaser
{
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationalFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImplementationFault))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class SystemFault : GeointegrasjonFault
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationalFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImplementationFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplicationFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidationFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FinderFault))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class GeointegrasjonFault
    {
        
        private string feilKodeField;
        
        private string feilBeskrivelseField;
        
        private string[] feilDetaljerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string feilKode
        {
            get
            {
                return this.feilKodeField;
            }
            set
            {
                this.feilKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string feilBeskrivelse
        {
            get
            {
                return this.feilBeskrivelseField;
            }
            set
            {
                this.feilBeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("liste", IsNullable=false)]
        public string[] feilDetaljer
        {
            get
            {
                return this.feilDetaljerField;
            }
            set
            {
                this.feilDetaljerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class Milepel
    {
        
        private string milepelNavnField;
        
        private string milepelBeskrivelseField;
        
        private System.DateTime milepelDatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string milepelNavn
        {
            get
            {
                return this.milepelNavnField;
            }
            set
            {
                this.milepelNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string milepelBeskrivelse
        {
            get
            {
                return this.milepelBeskrivelseField;
            }
            set
            {
                this.milepelBeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime milepelDato
        {
            get
            {
                return this.milepelDatoField;
            }
            set
            {
                this.milepelDatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KoordinatsystemKode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaseStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31")]
    public partial class Kode
    {
        
        private string kodeverdiField;
        
        private string kodebeskrivelseField;
        
        private bool erGyldigField;
        
        private bool erGyldigFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string kodeverdi
        {
            get
            {
                return this.kodeverdiField;
            }
            set
            {
                this.kodeverdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kodebeskrivelse
        {
            get
            {
                return this.kodebeskrivelseField;
            }
            set
            {
                this.kodebeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool erGyldig
        {
            get
            {
                return this.erGyldigField;
            }
            set
            {
                this.erGyldigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool erGyldigSpecified
        {
            get
            {
                return this.erGyldigFieldSpecified;
            }
            set
            {
                this.erGyldigFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class KoordinatsystemKode : Kode
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class FaseType : Kode
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class FaseStatus : Kode
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class Fase
    {
        
        private string faseNavnField;
        
        private string faseBeskrivelseField;
        
        private FaseType typeField;
        
        private FaseStatus statusField;
        
        private Milepel startMilepelField;
        
        private Milepel sluttMilepelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string faseNavn
        {
            get
            {
                return this.faseNavnField;
            }
            set
            {
                this.faseNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faseBeskrivelse
        {
            get
            {
                return this.faseBeskrivelseField;
            }
            set
            {
                this.faseBeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FaseType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FaseStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Milepel startMilepel
        {
            get
            {
                return this.startMilepelField;
            }
            set
            {
                this.startMilepelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Milepel sluttMilepel
        {
            get
            {
                return this.sluttMilepelField;
            }
            set
            {
                this.sluttMilepelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Saksnummer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Arkiv/Felles/xml.schema/2012.01.31")]
    public partial class Saksnoekkel
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Arkiv/Felles/xml.schema/2012.01.31")]
    public partial class Saksnummer : Saksnoekkel
    {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string saksaar
        {
            get
            {
                return this.saksaarField;
            }
            set
            {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string sakssekvensnummer
        {
            get
            {
                return this.sakssekvensnummerField;
            }
            set
            {
                this.sakssekvensnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidationFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FinderFault))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class ApplicationFault : GeointegrasjonFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class ValidationFault : ApplicationFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class FinderFault : ApplicationFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class OperationalFault : SystemFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class ImplementationFault : SystemFault
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", ConfigurationName="GiSakFaser.SaksfaserPort")]
    public interface SaksfaserPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GiSakFaser.SystemFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="SystemFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(GiSakFaser.ImplementationFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="ImplementationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(GiSakFaser.OperationalFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="OperationalFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(GiSakFaser.ApplicationFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="ApplicationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(GiSakFaser.FinderFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="FinderFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.FaultContractAttribute(typeof(GiSakFaser.ValidationFault), Action="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31/#HentFaserForSak", Name="ValidationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeointegrasjonFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saksnoekkel))]
        System.Threading.Tasks.Task<GiSakFaser.HentFaserForSakResponse> HentFaserForSakAsync(GiSakFaser.HentFaserForSak request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HentFaserForSak", WrapperNamespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", IsWrapped=true)]
    public partial class HentFaserForSak
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", Order=0)]
        public GiSakFaser.Saksnummer saksnummer;
        
        public HentFaserForSak()
        {
        }
        
        public HentFaserForSak(GiSakFaser.Saksnummer saksnummer)
        {
            this.saksnummer = saksnummer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HentFaserForSakResponse", WrapperNamespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", IsWrapped=true)]
    public partial class HentFaserForSakResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("liste", Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31", IsNullable=false)]
        public GiSakFaser.Fase[] @return;
        
        public HentFaserForSakResponse()
        {
        }
        
        public HentFaserForSakResponse(GiSakFaser.Fase[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SaksfaserPortChannel : GiSakFaser.SaksfaserPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SaksfaserPortClient : System.ServiceModel.ClientBase<GiSakFaser.SaksfaserPort>, GiSakFaser.SaksfaserPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SaksfaserPortClient() : 
                base(SaksfaserPortClient.GetDefaultBinding(), SaksfaserPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Saksfaser.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaksfaserPortClient(EndpointConfiguration endpointConfiguration) : 
                base(SaksfaserPortClient.GetBindingForEndpoint(endpointConfiguration), SaksfaserPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaksfaserPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SaksfaserPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaksfaserPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SaksfaserPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaksfaserPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GiSakFaser.HentFaserForSakResponse> GiSakFaser.SaksfaserPort.HentFaserForSakAsync(GiSakFaser.HentFaserForSak request)
        {
            return base.Channel.HentFaserForSakAsync(request);
        }
        
        public System.Threading.Tasks.Task<GiSakFaser.HentFaserForSakResponse> HentFaserForSakAsync(GiSakFaser.Saksnummer saksnummer)
        {
            GiSakFaser.HentFaserForSak inValue = new GiSakFaser.HentFaserForSak();
            inValue.saksnummer = saksnummer;
            return ((GiSakFaser.SaksfaserPort)(this)).HentFaserForSakAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Saksfaser))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Saksfaser))
            {
                return new System.ServiceModel.EndpointAddress("http://rep.geointegrasjon.no/Sak/Faser/xml.wsdl/2012.01.31");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SaksfaserPortClient.GetBindingForEndpoint(EndpointConfiguration.Saksfaser);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SaksfaserPortClient.GetEndpointAddress(EndpointConfiguration.Saksfaser);
        }
        
        public enum EndpointConfiguration
        {
            
            Saksfaser,
        }
    }
}
